### PR TITLE
[Interop layer] Fix charts

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

This PR fixes the data expectations between the interop layer and the charts. It also merges in the latest from `main` so that remaining interop layer work can happen on top of the latest release.

It probably makes the most sense to only review the last commit. Everything else is the merge from main.

### CODE REVIEW

**Comment by greg-does-weather** [comment]
Should we perhaps rebase the interop layer onto main instead of merging? There are more commits captured in this PR than I expected. I only expected the commits to `main` since we last rebased.

**Comment by jamestranovich-noaa** [comment]
I would suggest rebasing on `main` instead. It's confusing as-is...

**Comment by greg-does-weather** [comment]
I agree. I'm gonna put this on ice until we rebase the interop layer again.

**Comment by greg-does-weather** [comment]
superseded by #1898

**Pull request closed without merging**
