### PR TITLE
[Docker Setup] Fix permissions after each zap

### PR DESCRIPTION
**Pull request by eric-gade**
## What does this PR do? 🛠️
Should fix ownership in the docker container plus permissions on the directories locally. 

## What does the reviewer need to know? 🤔
This is kind of hacky, but the only way I could get it to work. We just run a couple of commands at the end of `zap`

### CODE REVIEW

**Review by greg-does-weather — APPROVED** [review]
You call it hacky, but I call it... well... I mean, ingenious but also hacky, but only hacky out of necessity.

hacking

**Review by jamestranovich-noaa — APPROVED** [review]
Ayup, a bit unfortunate we have to do this, but makes sense

**Comment by colinmurphy01** [comment]
Did this fix the docker issue?!?!?

**Comment by eric-gade** [comment]
@colinmurphy01 This _might_ have fixed one or several of our issues (it's hard to tell without using the system for a while). There are some other process concerns we have talked about regarding the database and switching branches, and I think we will formulate some lower priority tickets for those.

**Pull request merged**
