### PR TITLE
Change hourly forecast from 4 hours to 12

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

Just what it says on the tin.

## Screenshots (if appropriate): 📸

image

### CODE REVIEW

**Comment by eric-gade** [comment]
Do we want to link this is any way to https://github.com/weather-gov/weather.gov/pull/412 ?

**Comment by greg-does-weather** [comment]
For completeness, I'll repeat it here that I think we should prioritize #412 given ongoing discussion in Slack.

**Review by eric-gade — APPROVED** [review]
Aside from comments from design, this is 👍

**Comment by greg-does-weather** [comment]
Merging now so we can get this into beta.

**Pull request merged**
