### PR TITLE
Validate path parameters for our controlled routes

### LINKED ISSUE #530: Sanitize inputs instead of simply trusting them
Currently our location pages accept URL parameters (WFO, grid X, and grid Y) without verifying or cleaning them. We shouldn't do that. Since we only use them to pass along to the API, the result should only be that users get an error page, but we still shouldn't just do it.

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

- Adds route parameter validation to the `/points/{lat}/{lon}` and `/local/{wfo}/{x}/{y}` routes
  - Enforces that latitude and longitude are decimal numbers
  - Enforces that WFO is 3 alphabetic characters
  - Enforces that X and Y are integers
  - Any deviation results in a 404
- Adds WFO uppercasing to all the API calls that use the WFO because the API will give us a 500 if it's not uppercased
- Removes the location name from the end of the local route - it was only put there as a placeholder until we started fetching the name from the API (or possibly eventually somewhere else, but in any case, it's handled now)

Closes #530

## What does the reviewer need to know? 🤔

`make rebuild && make cc` maybe necessary. I can never tell what makes Drupal accept changes in this file.

### CODE REVIEW

**Comment by eric-gade** [comment]
@greg-does-weather When I test this locally, and I put in a junk value (http://localhost:8080/local/HNX/084/134/), I am getting the dreaded "This website encountered an error" page -- is that the intent? Or is there a 404 page we should be redirecting to?

**Comment by greg-does-weather** [comment]
Wow. It's the trailing slash. Uh... well... good catch. Let's see if I can figure out how to handle that. `:lolsob:`

**Comment by greg-does-weather** [comment]
Drupal won't create URLs with trailing slashes. By default, it simply doesn't permit them. There is an (unsupported?) [module](https://www.drupal.org/project/trailing_slash) that will enable it, but not only does it appear to be unsupported, but it also requires you to know exactly which URLs should be accepted with trailing slashes and we cannot know that. (Or if we could enumerate it, we wouldn't want to.)

Another possible solution would be to configure some redirects in Apache. It might be straightforward in cloud.gov (we already have [some Apache configuration](https://github.com/weather-gov/weather.gov/tree/main/.bp-config/httpd)), but I'm not sure how much effort it'd be to handle in other infrastructure.

The more I think about it, the more I think resolving it in the webserver is the right approach, but I'm just a little concerned about how we manage it such that we don't forget to make the same change in other environments.

**Comment by greg-does-weather** [comment]
@shadkeene Wanted to bring you into this one before we merge it because it makes a change that seems like it could be meaningful. As written, this PR would change what URL people get redirected to when they search for a location or use their browser location. Instead of being:

```
beta.weather.gov/local/PQR/104/114/Glide
```

it would not add the location name anymore:

```
beta.weather.gov/local/PQR/104/114
```

The URL part of the change is not necessary, but I originally added location name to the URL only because that was the only way I had handy to get it. Now that we're getting the location name from the API instead, we don't *need* it in the URL anymore, so I took it out as kind of a cleaning chore.

We can still do the validation we need to do without changing the URL behavior, so if you'd rather we keep the location name in the URL, that's a minor change.

**Review by eric-gade — COMMENTED** [review]
## Code Review Checklist

This is an automated comment on every pull request requiring a review. A checked item is either an assertion that I have tested this item or an indication that I have verified it does not apply to this pull request.

## The Basics
- [x] Checks are passing
- [x] I read the code
- [x] I ran the code
- [x] (if applicable) Post deploy steps are run
- [x] (if applicable) I validated the change on the deployed version in <environment>

## Documentation
- [x] changes to “how we do things” are documented in READMEs
- [x] all new functions and methods are commented using plain language
- [x] any new modules added documented in modules.md

## Security
- [x] security false positives are documented
- [x] data from external sources is cleaned and clearly marked

## Reliability
- [x] error handling exists for unusual or missing values
- [x] interactions with external systems are wrapped in try/except
- [x] functionality is tested with unit or integration tests
- [x] dependency updates in composer.json also got changed in composer-lock.json

## Infrastructure
- [x] all changes are auditable and documented via a script
- [x] it is clear who can and should run the script
- [x] (if applicable) diagrams have been updated or added in PlantUML

## Accessibility
- [x] New pages have been added to cypress-axe file so that they will be tested with our automated accessibility testing
- [x] Meets WCAG 2.0 AA or 2.1 AA for Section 508 compliance
    - [x] Site is keyboard accessible. All interactions can be accessed with a keyboard
    - [x] Site is free of keyboard traps. The keyboard focus is never trapped in a loop
    - [x] All form inputs have explicit labels
    - [x] Form instructions are associated with inputs
    - [x] All relevant images use an img tag
    - [x] All images have appropriate alt attributes
    - [x] Multimedia is tagged. All multimedia has appropriate captioning and audio description
    - [x] Text has sufficient color contrast. All text has a contrast ratio of 4.5:1 with the background
    - [x] Site never loses focus. Focus is always visible when moving through the page with the keyboard
    - [x] Tab order is logical
    - [x] Tables are coded properly. Tables have proper headers and column attributes
    - [x] Headings are nested properly. Heading elements are nested in a logical way
    - [x] Language is set. The language for the page is set
    - [x] CSS is not required to use the page. The page makes sense with or without CSS
    - [x] Links are unique and contextual. All links can be understood taken alone, e.g., ‘Read more - about 508’
    - [x] Page titles are descriptive

## Device Matrix
- [x] firefox/gecko (renders correctly and user interactions work)
- [x] chrome/chromium/edge (renders correctly and user interactions work)
- [x] safari/webkit (renders correctly and user interactions work)
- [x] web page is readable and usable 
    - [x] at 480px     (mobile)
    - [x] at 640px     (tablet)
    - [x] at 1024px    (desktop)

**Review by loganmcdonald-noaa — APPROVED** [review]

**Pull request merged**
