### PR TITLE
Software stack diagram

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What's wrong?

We don't have one.

## How does this PR fix it? 

Adds one.

I don't know PlantUML but I can muddle through well enough for a basic block diagram. Our software stack is also really short and simple. In fact, I'm not sure there's value in having this diagram. Just saying "Drupal" seems like it captures our stack to me, but maybe I'm leaving out details?

## Screenshots (if appropriate):

diagram

### CODE REVIEW

**Comment by greg-does-weather** [comment]
Addresses #18

**Comment by colinmurphy01** [comment]
@mgwalker following up on some comments I left. I'll approve the review, but it's up to you if you think they need to be addressed or not.

**Review by colinmurphy01 — APPROVED** [review]

**Comment by greg-does-weather** [comment]
@colinmurphy01 This is a draft PR. It's not ready for review.

**Comment by greg-does-weather** [comment]
Closing this in favor of the diagram in #328

**Pull request closed without merging**
