### PR TITLE
Combo box aria description

### PR DESCRIPTION
**Pull request by eric-gade**
## What does this PR do? 🛠️
Deals with #1059 where there wasn't a matching element with aria-descrption text.

## What does the reviewer need to know? 🤔
I _think_ this was pretty straightforward? But am slightly suspicious.

## Screenshots (if appropriate): 📸
Screen Shot 2024-05-01 at 12 52 33 PM

### CODE REVIEW

**Comment by partly-igor** [comment]
It seems like this might be creating a duplicate text description that's read after the screen reader focus has moved away from the combo box

Screenshot of voiceover text moved after the combo box

**Comment by partly-igor** [comment]
Duplicate in the sense that it's similar to "Enter city or zip code"

**Comment by eric-gade** [comment]
@partly-igor I'm wondering: do we actually need an `aria-describedby` attribute on the input at all? Seems like the label above the component does the trick on its own, plus most screenreaders will have general guidance for the combobox role anyway

**Comment by partly-igor** [comment]
I think you are right we may not need it all.

**Review by greg-does-weather — APPROVED** [review]

**Pull request merged**
