### PR TITLE
Add documentation about how to export and import content

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

Documents the process of importing and exporting content.

### CODE REVIEW

**Comment by greg-does-weather** [comment]
@kmranjo We can pair up on reviewing this if it's helpful!

**Comment by kmranjo** [comment]
@greg-does-weather  Yes, could we set up some time? Both to review/discuss and also because I'm not entirely sure what to do with a pull review request (I dont think I've done one yet in github?).

**Comment by greg-does-weather** [comment]
@kmranjo Based on our conversation yesterday, I made an attempt at plain-languaging our environments documentation, moved the warning about configuration changes to the top of the sync doc, and removed the rest of the configuration documentation since it's probably not applicable to the target audience.

**Review by kmranjo — APPROVED** [review]
I think this looks good! We may want to consider spelling out more explicitly that content doesn't have to be created in staging first and then pushed to production, but only in certain circumstances. I think that might be something that can go in a separate doc more about content management as a whole though.

**Pull request merged**
