### PR TITLE
Add WFO promo content type and associated rendering

### LINKED ISSUE #597: WFO Promo Component
Build ticket based on outcomes of #181 

### Goals
Provide a quick introduction to the WFO responsible for the forecast, with a quick path to contact the office or learn more about it.

### Related user needs
1.1 - I want to know how NWS serves my priorities
1.2 - I want to know who creates forecasts and hazards, and how they create them
6.1 - As a partner, I want to know who and how I can reach out to someone when I need to

### Dependencies
Need to settle on a method by which we associate a piece of content with a specific WFO (tagging? dropdown? other?)

### Content
All content is authored in the CMS
- WFO shortcode (required, but may be auto populated, eng TBD)
- WFO name (required, but may be auto populated, eng TBD)
- URL to WFO page (required)
- WFO phone number (optional)
- Short intro text (required, 150 characters)
- URL to WFO Facebook page (optional)
- URL to WFO Twitter account (optional)
- URL to WFO YouTube account (optional)

WFO Name is an H2
Intro text is plain text only, no styling elements needed

### Behavior
- Any optional fields not authored do not appear in the published component 
- For social media links, the icon for the platform appears only if the URL for that platform is authored 
- The component cannot be published if required fields are not authored 
- Only one instance of the component can exist for each WFO 
- Display conditions: For any location page, the system detects which WFO covers that location and populates the corresponding instance of this component 

### Acceptance Criteria 
Site users should be able to
- Navigate to their location page via search or direct link
- View the component on the page
- Read the text (heading, WFO name, intro, phone number, social media promos) 
- View the images (social media icons) 
- Click the phone number to call from any call-capable device 
- Click the WFO name to navigate to the WFO page 
- Click any social media icon to navigate to the social account for that office 
- Content creators should be able to 

Open the WFO promo component tagged for their WFO
- Author content within the component 
- Publish the component 

Content admins should be able to
- Create a new WFO promo component 
- Tag the component for a WFO (or select from menu) 

[Example captured in document](https://docs.google.com/document/d/1_BzB1kA8jrzfVrXYoiq2juyEzKaTBWtmjetmDJzw7T0/edit#heading=h.80gjkxm4vd6h)

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

- Adds a `WFO Promo` content type
  - the `title` field is renamed to "WFO name" - Drupal requires all nodes to have a non-null `title` field, so that seems like a perfect repurposing, especially since it also lets us change the displayed name.
  - @kmranjo: The Twitter URL optional field is instead named "Twitter/X URL" – what do you think? I figure "Twitter" is still used in regular conversation so it'd be clearer to content authors what we're asking for.
- Adds a `WFOPromoBlock` class, based heavily on the weather story block
  - Factored out some common functionality into a trait, but I don't think that's what I really want to do. It works for now, but in the near future (incoming PR, in fact), I want to move it into a service so we can mock it in the block tests. Hopefully it'll lead to less test setup code.
- Updates USWDS to get the X icon
  - This update causes the current conditions component to go funky with the `℉` display. But since there's already an issue to overhaul the current conditions component, I didn't see the point in trying to fix it. (looks like #692 is ready, in fact, so maybe after that's merged)
- Fixes the admin theme so it properly hides the fields we don't want authors to see for the weather story form (got boofed in #660, when we removed the old "weather narrative" content type and added the "weather story" content type).

Closes #597

## What does the reviewer need to know? 🤔

`make import-config` for sure – maybe even twice, why not? – and probably `make cc`

## Screenshots (if appropriate): 📸

(note the mobile and desktop screenshots are out of date because the Twitter logo has been replaced with the X logo, but I didn't capture new screenshots)

<details>
<summary>authoring UI </summary>

Screenshot 2024-01-22 at 15-57-56 Create WFO Promo Weather gov

</details>

<details>
<summary>mobile</summary>

Screenshot 2024-01-22 at 15-55-50 Weather gov National Weather Service

</details>

<details>
<summary>desktop</summary>

Screenshot 2024-01-22 at 15-55-01 Weather gov National Weather Service

</details>

### CODE REVIEW

**Comment by kmranjo** [comment]
I think that makes sense! Agree, Twitter is definitely used more commonly, so good to include for clarity.

**Comment by greg-does-weather** [comment]
I think #692 fixes the current conditions bug caused by updating USWDS, so shouldn't be any worries there. Once that one is merged into main, I'll merge it into this one and confirm.

**Comment by eric-gade** [comment]
@greg-does-weather I am able to create a WFO promo and have it link to my local WFO correcly (huzzah!). But the title forms a link that leads to a "page not found" -- I guess that's the specific WFO page (`http://localhost:8080/office/OKX/` in my case)

**Review by eric-gade — APPROVED** [review]
Code lgtm 👍 
  
Regarding the WFO node interaction trait: I think it's fine to have this as a trait. In fact, we will probably need some more manual node interaction traits all around, now that we have the separate location page setup. The issue with making this a service instead is that it will show up in the admin UI as a plugin right?
  
Anyway none of that is blocking!
    
## Code Review Checklist
## The Basics
- [x] Checks are passing
- [x] I read the code
- [x] I ran the code
- [ ] (if applicable) Post deploy steps are run
- [ ] (if applicable) I validated the change on the deployed version in <environment>

## Documentation
- [ ] changes to “how we do things” are documented in READMEs
- [x] all new functions and methods are commented using plain language
- [ ] any new modules added documented in modules.md

## Security
- [ ] security false positives are documented
- [ ] data from external sources is cleaned and clearly marked

## Reliability
- [ ] error handling exists for unusual or missing values
- [ ] interactions with external systems are wrapped in try/except
- [ ] functionality is tested with unit or integration tests
- [x] dependency updates in composer.json also got changed in composer-lock.json

## Infrastructure
- [x] all changes are auditable and documented via a script
- [x] it is clear who can and should run the script
- [ ] (if applicable) diagrams have been updated or added in PlantUML

## Accessibility
- [ ] New pages have been added to cypress-axe file so that they will be tested with our automated accessibility testing
- [x] Meets WCAG 2.0 AA or 2.1 AA for Section 508 compliance
    - [ ] Site is keyboard accessible. All interactions can be accessed with a keyboard
    - [ ] Site is free of keyboard traps. The keyboard focus is never trapped in a loop
    - [ ] All form inputs have explicit labels
    - [ ] Form instructions are associated with inputs
    - [ ] All relevant images use an img tag
    - [ ] All images have appropriate alt attributes
    - [ ] Multimedia is tagged. All multimedia has appropriate captioning and audio description
    - [x] Text has sufficient color contrast. All text has a contrast ratio of 4.5:1 with the background
    - [x] Site never loses focus. Focus is always visible when moving through the page with the keyboard
    - [x] Tab order is logical
    - [x] Tables are coded properly. Tables have proper headers and column attributes
    - [x] Headings are nested properly. Heading elements are nested in a logical way
    - [x] Language is set. The language for the page is set
    - [x] CSS is not required to use the page. The page makes sense with or without CSS
    - [x] Links are unique and contextual. All links can be understood taken alone, e.g., ‘Read more - about 508’
    - [x] Page titles are descriptive

## Device Matrix
- [x] firefox/gecko (renders correctly and user interactions work)
- [x] chrome/chromium/edge (renders correctly and user interactions work)
- [ ] safari/webkit (renders correctly and user interactions work)
- [x] web page is readable and usable 
    - [x] at 480px     (mobile)
    - [x] at 640px     (tablet)
    - [x] at 1024px    (desktop)

**Comment by greg-does-weather** [comment]
Not necessarily! We could add another service to the WeatherDataService module. (Which this PR now does since merging in the test PR too.)

Also, we've decided to stick with the 404 for WFO pages for now since we don't know where they ought to go. But I'm sure we'll address that soon.

**Pull request merged**
