### PR TITLE
Add a `/bundle` endpoint to fully capture all the API data in a single page load

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

The API proxy server now has an endpoint at [localhost:8081/bundle](http://localhost:8081/bundle) that will enable capturing a "bundle" of API responses associated with the same page load. The result is a ZIP file that we can share more easily. Just unzip it locally and then visit the same location page that generated the bundle. (You may have to clear your Drupal cache first, or wait a minute or so for them to expire.)

Also adds a header to our outgoing API requests identifying the Drupal response we're servicing. That's necessary for the whole "bundling" thing, but we might other uses for it in the future. It's not a personal identifier – it's based on the current time.

### CODE REVIEW

**Comment by eric-gade** [comment]
I spent a bit of time trying to figure out why I couldn't get the bundle to save, then remembered that the `/local/TST/10/10` test route uses the proxy to fetch preloaded data. That seems to actually crash Drupal and no subsequent requests to the main web server work. This might be because the proxy server itself is also crashing.
  
The server(s?) also crashed in the case where I activated the bundle saving, then went to another tab and simply refreshed a page I had already loaded. I'm thinking this has to do with the fact that we are loading from the cache and not making any api requests at all, though looking at the code I'm not sure why that should crash anything rather than simply not writing a saved bundle.

**Comment by greg-does-weather** [comment]
Good debug info! Thank you! Will look into it.

**Comment by greg-does-weather** [comment]
Alright, so I think everything you saw was a result of the way I was handling ending a bundle. Basically, if you enabled a bundle, it would disable itself automatically after 3 seconds. The original assumption was you'd turn it on, run your requests, and that'd be that, and I needed a way for the server to know that the bundle was finished. Instead of centralizing that, I tried to make both the main and save components track it, and when they got out of sync, it was a bad time for everyone.

I just pushed up a commit that centralizes configuration into one place. Now main doesn't need to worry about it, and the save component is responsible for signaling when the bundle is finished.

There was also a logic error where if bundling was enabled, it would try to skip reading local files, which is very silly.

**Review by eric-gade — APPROVED** [review]
👍

**Pull request merged**
