### PR TITLE
Support redirecting from URLs with place names

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

Adds a new `/place/{state}/{city}` route. We look the state/city up in our places database and then redirect to the lat/lon URL.

- related to #496

### CODE REVIEW

**Review by loganmcdonald-noaa — APPROVED** [review]

**Comment by greg-does-weather** [comment]
I think we're holding this for now. Is that right, @colinmurphy01?

**Comment by colinmurphy01** [comment]
Yea, this was an idea. I'd love for @kmranjo to weigh in on the strategy here a little more and if we need a second opinon, we can bring in my supe.

**Comment by greg-does-weather** [comment]
One thing I'll note is that by doing this, we could conceivably add all of the ~22,000 places in our database to our sitemap so search engines can find them. We cannot realistically add all of the grid points to a sitemap.

**Comment by kmranjo** [comment]
Having readable place names in the URL can certainly help with SEO, but I don't think its make or break if there are drawbacks. I'm also not sure how we would do places that aren't as simple as state/city. Things like counties, mountains, etc where lat/long points might work better?

**Comment by greg-does-weather** [comment]
This conversation really intrigues me because I don't see any downside to adding this. Whether it serves SEO value and whether/how we extend it to support other place types, it only seems like a net good. The code to support it is tiny and easy to maintain.

I'm not gonna make a stink about it or anything, to be clear. I'm fine with letting it ripen, I'm just not clear on how it's unripe. 😂

**Comment by colinmurphy01** [comment]
Appreciate the nudge.

In summary:
- it'll improve SEO
- it's easy to maintain and expand if needed
- low-no risk in implementing now

If that's the case, let's deploy it. Any objections?

CC @coreypieper @shadkeene

**Pull request merged**
