### PR TITLE
Add a beta alert banner

### PR DESCRIPTION
**Pull request by greg-does-weather**
## What does this PR do? 🛠️

Adds a big ol' beta banner.

## What does the reviewer need to know? 🤔

This PR isn't tied to a ticket. It just seemed like a good idea (and was an excuse to fiddle with some other Drupal stuff).

- @shadkeene (and Kari, but I couldn't find her in GitHub): Is this something we should have?
- @kmranjo: I just made up some text and plopped it at the top of the page. Now there's a placeholder for someone who knows what they're doing to tell me what the text should be and where it should go!

## Screenshots (if appropriate): 📸

image

### CODE REVIEW

**Comment by kmranjo** [comment]
@greg-does-weather  Nice! Maybe simplify some of the language a little. What about this? Would want to get Shad's ok on it as well. 

This is a beta site. 
It’s an early, in-progress version of an improved weather.gov, and should not be used for critical decision making. 
https://weather.gov/ remains the authoritative source of weather information.

**Comment by shadkeene** [comment]
@greg-does-weather and @kmranjo agreed.  I like it!  But yes, please make it a smaller footprint and I like Katrina's suggestion.  You can remove the "critical" too, for now.

**Comment by greg-does-weather** [comment]
Updated, per conversation here and in Slack.

image

**Review by claire-skies-noaa — APPROVED** [review]

**Comment by claire-skies-noaa** [comment]
Also tested in Microsoft Edge. Looks good 👍

**Pull request merged**
