### PR TITLE
Adding How we work doc and Roadmap updates

### PR DESCRIPTION
**Pull request by colinmurphy01**
## What does this PR do? 🛠️

- Documenting our working processes
- Updating roadmap with milestone resources

### CODE REVIEW

**Comment by greg-does-weather** [comment]
@colinmurphy01 What do you need by way of review?

**Comment by colinmurphy01** [comment]
@greg-does-weather good question, thanks for revisiting.

It's been a while since we discussed this. So I wanted leads to signoff on the process overview.

CC @igorkorenfeld @shadkeene

**Review by mgwalker — APPROVED** [review]

**Review by greg-does-weather — APPROVED** [review]

**Review by igorkorenfeld — APPROVED** [review]
Looks good!

**Review by partly-igor — APPROVED** [review]
Used the wrong account, but still looks good!

**Comment by colinmurphy01** [comment]
@shadkeene approved [in slack](https://gsa-tts.slack.com/archives/C05DU11D4J2/p1709232937525319)

**Pull request merged**
